[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
monitor_speed = 921600
build_unflags = -Os
build_flags = 
	-O3
	-funroll-loops
	-ffast-math
	-I.pio/build/rpipico2/pioasm
lib_deps = 
	jgromes/RadioLib@^7.7.1
	fastled/FastLED@^3.10.3
	https://github.com/adafruit/Adafruit_BMP3XX
	https://github.com/adafruit/adafruit_lsm6ds
	https://github.com/sparkfun/SparkFun_LSM6DSV16X_Arduino_Library
	mikalhart/TinyGPSPlus@^1.1.0
